version: '2.2'
services:
  eatit:
#    build:
#      context: .
#      dockerfile: dockerfiles/production/Dockerfile
    image: eatit:prod
    ports:
      - "80:8080"
    environment:
      ROOT_URL: http://localhost
      MONGO_URL: mongodb://db:27017
  db:
    image: mongo